//User 1
POST http://localhost:8080/login?username=aramesh&password=1234

###
POST http://localhost:8080/up_pic_profile
Authorization: Bearer VsLLLRC5Fj5CLecQl6Faui1ordB0PIDEpvjZkovL//5NE15gBnOT9EIlcv+QBib3
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Aramesh.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/UserProfile/Aramesh.jpg
--WebAppBoundary--
###

//User 2
POST http://localhost:8080/login?username=aria&password=1234

###
POST http://localhost:8080/up_pic_profile
Authorization: Bearer GVQzeKzn3S37sbKXorMHCO3EjndjUFFEXMEb01DYDxA3CPfdQbiqG5PJlGin/Lpl
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="aria.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/UserProfile/aria.jpg
--WebAppBoundary--
###

//User 3
POST http://localhost:8080/login?username=azarakhsh&password=1234

###
POST http://localhost:8080/up_pic_profile
Authorization: Bearer 3Cwo2kMW6YnfIuv1NKkWA0dxCjIkLyHc8IEyJ9FoqE1ms1GWV7I/Tg/gwetx3T1e
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Azarakhsh.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/UserProfile/Azarakhsh.jpg
--WebAppBoundary--
###

//User 4
POST http://localhost:8080/login?username=cityaway&password=1234

###
POST http://localhost:8080/up_pic_profile
Authorization: Bearer uE6spJK1+X9QWqTEgtABq9z4aaBmwRfonHj2/pzWv7zlJ5T8Q9YqjAcBWBBz5AgK
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="CityAway.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/UserProfile/CityAway.jpg
--WebAppBoundary--
###

//User 5
POST http://localhost:8080/login?username=famile_door&password=1234

###
POST http://localhost:8080/up_pic_profile
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Famile_Door.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/UserProfile/Famile_Door.jpg
--WebAppBoundary--
###

//User 6
POST http://localhost:8080/login?username=galaxy&password=1234

###
POST http://localhost:8080/up_pic_profile
Authorization: Bearer d5xJEsW5jwvblLN80u+JTpXagLtYID9xSvisBvg9LOEEkq0V3bE2n19VVoz468L8
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Galaxy.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/UserProfile/Galaxy.jpg
--WebAppBoundary--
###

//User 7
POST http://localhost:8080/login?username=hightech&password=1234

###
POST http://localhost:8080/up_pic_profile
Authorization: Bearer VYbRjBw4NMtNwgFQLLWpcV1s16a+PZyklTk5zxxeBmeVWJHtSTBhibbGoiACKQ3M
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="HighTech.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/UserProfile/HighTech.jpg
--WebAppBoundary--
###

//User 8
POST http://localhost:8080/login?username=inside___&password=1234

###
POST http://localhost:8080/up_pic_profile
Authorization: Bearer qkDoqq3vv6Adw8EZzdkHZmQBYSenli72Citoh/P5uxXVodXOza3wWKnp/VoEy/Lu
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Inside___.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/UserProfile/Inside___.jpg
--WebAppBoundary--
###

//User 9
POST http://localhost:8080/login?username=max_pic&password=1234

###
POST http://localhost:8080/up_pic_profile
Authorization: Bearer FaZI3j20Hf9JoFxzcN98COZsvEBVeW9TAjI64MtF2OfbY1tF0Qrf8wuMAO9timNo
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Max.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/UserProfile/Max.jpg
--WebAppBoundary--
###

//User 10
POST http://localhost:8080/login?username=me_you&password=1234

###
POST http://localhost:8080/up_pic_profile
Authorization: Bearer a8ZxXbfCvlqSc1NPF16Qg2y5Riu2cj4hXN0C8kGBxa56g1rYtOdHiMXOzfrw49zr
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Me_You.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/UserProfile/Me_You.jpg
--WebAppBoundary--
###

//User 11
POST http://localhost:8080/login?username=milad&password=1234

###
POST http://localhost:8080/up_pic_profile
Authorization: Bearer rVCF5dwHpbKDk81OkbVdaltkv/8fdHXElv5QwivodN2Lt4Y1qa+p13iTz+O8ZaxP
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="milad.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/UserProfile/milad.jpg
--WebAppBoundary--
###

//User 12
POST http://localhost:8080/login?username=phanoos&password=1234

###
POST http://localhost:8080/up_pic_profile
Authorization: Bearer x/7eW4pWS2NPh0Ka5CF6SMOBpja8bPwBSw7RsbnC9TxvduSwt1MbxQk2pBUwmf4H
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Phanoos.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/UserProfile/Phanoos.jpg
--WebAppBoundary--
###
