//User 1
POST http://localhost:8080/register?username=aramesh&password=1234&bio=در تنهایی ابدی ات به سکوت گوش فرا بده که دروازه ای به سوی آرامش جهان است

###

//User 2
POST http://localhost:8080/register?username=aria&password=1234&bio=قهرمان خودت باش
###

//User3
POST http://localhost:8080/register?username=azarakhsh&password=1234&bio=سپیده دم همه ستاره هاست
###

//User 4
POST http://localhost:8080/register?username=cityaway&password=1234&bio=
###

//User 5
POST http://localhost:8080/register?username=famile_door&password=1234&bio=🔸پیج رسمی فامیل دور 🔸 🔹بهترین جملات و لحظات طنز و مفهوم دار فامیل دور🔹
###

//User 6
POST http://localhost:8080/register?username=galaxy&password=1234&bio=شکوه کهکشان
###

//User 7
POST http://localhost:8080/register?username=hightech&password=1234&bio=اخبار روز دنیای فناوری
###

//User 8
POST http://localhost:8080/register?username=inside___&password=1234&bio=شَرحی ِز حال و حالی زِ شَرح نیست🖤🥀
###

//User 9
POST http://localhost:8080/register?username=max_pic&password=1234&bio=Max
###

//User 10
POST http://localhost:8080/register?username=me_you&password=1234&bio=خودمو واسه کسی نگه میدارم که دعا میکنه تا ابد با من باشه ⎈☻
###

//User 11
POST http://localhost:8080/register?username=milad&password=1234&bio=شهر من دنیای من
###

//User 12
POST http://localhost:8080/register?username=phanoos&password=1234&bio=من از اینجا خواهم رفت و فرقی هم نمیکند که فانوسی داشته باشم یا نه! کسی که میگریزد از گم شدن نمیترسد
###
