//aria 1
POST http://localhost:8080/post
Authorization: Bearer GVQzeKzn3S37sbKXorMHCO3EjndjUFFEXMEb01DYDxA3CPfdQbiqG5PJlGin/Lpl
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

.
ببین … من هیولا نیستم …
من فقط یه وضعیت بحرانی ام …‌
جوکر۲۰۱۹ شباهت های زیادی داره به حال و روز مردم ایران . نمیدونم چقدر با این فیلم ارتباط برقرار کردین ولی همه ی ما یک جوکر درون داریم.یه انسان غمگین، خشمگین،خسته،دارای حال بحرانی  و در عین حال خنده ی مصنوعی روی لب!
نمیدونم چی میشه کرد. گاهی آدم دیگه توان ادامه دادن و فکر کردن رو نداره.گاهی نداشتنِ توان ادامه دادن مشکلات باعث اتفاق های وحشتناک میشه... هرچقدر هم صبور باشی روزی کاسه ی صبرت لبریز میشه.


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-32-36_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-32-36_UTC.jpg
--WebAppBoundary--

###

//aria 2
POST http://localhost:8080/post
Authorization: Bearer GVQzeKzn3S37sbKXorMHCO3EjndjUFFEXMEb01DYDxA3CPfdQbiqG5PJlGin/Lpl
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

💠کوه های آلاداغ لار_تبریز

این همه رنگ و زیبایی رو فقط در کوه های آلاداغ لار ببینی و چقدر به وجد میای و کیف میکنی👌

کوه و تپه‌های رسی آلا‌داغ‌لار، کوه‌های رنگارنگی به رنگ قهوه‌ای، سبز، قرمز، زرد، نارنجی و سفید هستند که وقتی بارندگی می‌شود و خاک رس این کوه‌ها خیس می‌شود، چشم‌اندازی بسیار دیدنی ایجاد می‌کنند. این شگفتی‌ آفرینش از نزدیکی میانه شروع می‌شود و تا مسیر اهر به تبریز ادامه دارد.

آدرس: ایران، استان آذربایجان شرقی، ۲۵ کیلومتری شمال شرقی تبریز، کنار شهرستان خواجه

#ایرانی #ایرانگردی #سفر #مسافرت #طبیعت🌱🌳🍃


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-33-32_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-33-32_UTC.jpg
--WebAppBoundary--

###

//aria 3
POST http://localhost:8080/post
Authorization: Bearer GVQzeKzn3S37sbKXorMHCO3EjndjUFFEXMEb01DYDxA3CPfdQbiqG5PJlGin/Lpl
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

گاهی دلت میخواهد از دید بعضی  آدمها پنهان بمانی...!!
#طبیعت


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-34-16_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-34-16_UTC.jpg
--WebAppBoundary--

###

//aria 4
POST http://localhost:8080/post
Authorization: Bearer GVQzeKzn3S37sbKXorMHCO3EjndjUFFEXMEb01DYDxA3CPfdQbiqG5PJlGin/Lpl
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

گەشتێک لە سروشتی جوانی شاری سەردەشت و تاڤگەی شەڵماش وێڕای دۆستانی ئازیز.
.
سپاس لە جوانڕۆ قادریان و سەرجەم هونەرمەندانی سەردەشت بۆ میوانداری خۆمانە و پڕ لە موحەبەتیان
.
سپاس بۆ سینای ئازیز لەبەر وێنە جوانەکانی لێی گرتین
.

سفری بە طبیعت زیبای شهرستان سردشت و آبشار شلماش به همراه دوستان عزیز و یاران موافق!
.

#طبیعت

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-34-56_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-34-56_UTC.jpg
--WebAppBoundary--

###

//aria 5
POST http://localhost:8080/post
Authorization: Bearer GVQzeKzn3S37sbKXorMHCO3EjndjUFFEXMEb01DYDxA3CPfdQbiqG5PJlGin/Lpl
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain



--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-35-56_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-35-56_UTC.jpg
--WebAppBoundary--

###

//aria 6
POST http://localhost:8080/post
Authorization: Bearer GVQzeKzn3S37sbKXorMHCO3EjndjUFFEXMEb01DYDxA3CPfdQbiqG5PJlGin/Lpl
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

هیچ درختی
به خاطر پناه دادن به کبوترها
بی بار و برگ نشده است
تکیه گاه باشیم
مهربانی سخت نیست🍀🌼
 ‎‌‌‌‌‌‌ ‌‌‌‌‌‌‌‌‌‌‌‌ ‎‌‌‌‌‌‌ ‌‌‌‌‌‌‌‌‌‌‌‌ ‎‌‌‌‌‌‌ ‌‌‌‌.
.

#آرامش #زمین #دنیا #طبیعت #درخت #جنگل #دریا #آسمان


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-39-04_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-39-04_UTC.jpg
--WebAppBoundary--

###

//aria 7
POST http://localhost:8080/post
Authorization: Bearer GVQzeKzn3S37sbKXorMHCO3EjndjUFFEXMEb01DYDxA3CPfdQbiqG5PJlGin/Lpl
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

.
#طبیعت #طبیعتگردی #طبیعت_زیبا #طبیعت_ایران #پاییزی #پاییزانه #خورشید


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-39-51_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-39-51_UTC.jpg
--WebAppBoundary--

###

//aria 8
POST http://localhost:8080/post
Authorization: Bearer GVQzeKzn3S37sbKXorMHCO3EjndjUFFEXMEb01DYDxA3CPfdQbiqG5PJlGin/Lpl
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

موتور کرج🇮🇷 .
.
#تهران #ایران #طبیعت #عشق


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-40-27_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-40-27_UTC.jpg
--WebAppBoundary--

###

//aria 9
POST http://localhost:8080/post
Authorization: Bearer GVQzeKzn3S37sbKXorMHCO3EjndjUFFEXMEb01DYDxA3CPfdQbiqG5PJlGin/Lpl
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

دشت آفتاب گردان کالپوش-شاهرود
جاهای دیدنی و بکر ایران و جهان

#طبیعت
#آبشار
#گل
#دریا
#کوه
#جنگل


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-47-04_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-47-04_UTC.jpg
--WebAppBoundary--

###

//aria 10
POST http://localhost:8080/post
Authorization: Bearer GVQzeKzn3S37sbKXorMHCO3EjndjUFFEXMEb01DYDxA3CPfdQbiqG5PJlGin/Lpl
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

معرفی جاهای دیدنی و بکر ایران و جهان

#طبیعت
#آبشار
#گل
#دریا
#کوه
#جنگل


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-48-34_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-48-34_UTC.jpg
--WebAppBoundary--

###