//azarakhsh 1
POST http://localhost:8080/post
Authorization: Bearer 3Cwo2kMW6YnfIuv1NKkWA0dxCjIkLyHc8IEyJ9FoqE1ms1GWV7I/Tg/gwetx3T1e
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

فردا دیر است ...
امروزت را همین امروز ، زندگی کن !
همین امروز لذتش را ببر ،
و همین امروز برای آرزوهایت تلاش کن ...
حسرت ، یعنی در گذشته جا مانده ای ،
و نگرانی یعنی ، اسیرِ آینده ای شده ای که هنوز نرسیده و اتفاقاتی که هنوز نیفتاده !
آینده ای که شاید نرسد
و اتفاقاتی که شاید نیفتد !
بیخیالِ چیزهایی که نبودنشان کیفیتِ بودنت را کم می کند
آرامش و لبخند را در آغوش بگیر و امروز را همان جوری که دوست داری زندگی کن ...


#آرامش #زیبا #عکاس #عکاسی #پروفایل #طبیعت


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-27-44_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/profile/2020-09-19_21-27-44_UTC.jpg
--WebAppBoundary--

###

//azarakhsh 2
POST http://localhost:8080/post
Authorization: Bearer 3Cwo2kMW6YnfIuv1NKkWA0dxCjIkLyHc8IEyJ9FoqE1ms1GWV7I/Tg/gwetx3T1e
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

تو را در باد گم کرد و به انتظار نشست و نمی دانست مسافران باد را بازگشتی نیست . . 💔

#پروفایل


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-33-01_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/profile/2020-09-19_21-33-01_UTC.jpg
--WebAppBoundary--

###

//azarakhsh 3
POST http://localhost:8080/post
Authorization: Bearer 3Cwo2kMW6YnfIuv1NKkWA0dxCjIkLyHc8IEyJ9FoqE1ms1GWV7I/Tg/gwetx3T1e
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

.
چقدر هیچ حرفی نداریم که با هیچ کس بزنیم ...
یاد این شعر افتادم : دلتنگمو و با هیچکسم میل سخن نیست ...
کسی هست باهاش حرف بزنین ؟

#پروفایل


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-34-12_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/profile/2020-09-19_21-34-12_UTC.jpg
--WebAppBoundary--

###

//azarakhsh 4
POST http://localhost:8080/post
Authorization: Bearer 3Cwo2kMW6YnfIuv1NKkWA0dxCjIkLyHc8IEyJ9FoqE1ms1GWV7I/Tg/gwetx3T1e
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

عکس پروفایل(تنهایی)

#هنر #هنرمند #گرافیک #پروفایل #عکس #عکاسی #نقاشی #طراحی #زمین


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-38-58_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/profile/2020-09-19_21-38-58_UTC.jpg
--WebAppBoundary--

###

//azarakhsh 5
POST http://localhost:8080/post
Authorization: Bearer 3Cwo2kMW6YnfIuv1NKkWA0dxCjIkLyHc8IEyJ9FoqE1ms1GWV7I/Tg/gwetx3T1e
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

👇👇متن هایی که آرومت میکنه 🥀 کافه تکست
______________
#شعر


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-44-28_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/profile/2020-09-19_21-44-28_UTC.jpg
--WebAppBoundary--

###

//azarakhsh 6
POST http://localhost:8080/post
Authorization: Bearer 3Cwo2kMW6YnfIuv1NKkWA0dxCjIkLyHc8IEyJ9FoqE1ms1GWV7I/Tg/gwetx3T1e
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

دریای آروم ازت ناخدای باتجربه و حرفه ای نمیسازه!
🚢🌊
.
.

#عکس #عکاسی #دریا #غروب_خورشید #طبیعت #تهران  #پروفایل


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-58-10_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/profile/2020-09-19_21-58-10_UTC.jpg
--WebAppBoundary--

###

//azarakhsh 7
POST http://localhost:8080/post
Authorization: Bearer 3Cwo2kMW6YnfIuv1NKkWA0dxCjIkLyHc8IEyJ9FoqE1ms1GWV7I/Tg/gwetx3T1e
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain



--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_22-07-33_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/profile/2020-09-19_22-07-33_UTC.jpg
--WebAppBoundary--

###

