//Aramesh 1
POST http://localhost:8080/post
Authorization: Bearer VsLLLRC5Fj5CLecQl6Faui1ordB0PIDEpvjZkovL//5NE15gBnOT9EIlcv+QBib3
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

Falls
.
.
.
#waterfalls #falls #nature #landscape #طبیعت #آبشار #سیاه_سفید


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-17_19-06-49_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-17_19-06-49_UTC.jpg
--WebAppBoundary--

###

//Aramesh 2
POST http://localhost:8080/post
Authorization: Bearer VsLLLRC5Fj5CLecQl6Faui1ordB0PIDEpvjZkovL//5NE15gBnOT9EIlcv+QBib3
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

🌿زادگاه:
 مناطق شرقی و جنوبی افریقا.

🏜شرایط نگهداری:
آب گلدان بايد به طور کامل خشك و پس از خشک شدن دوباره آبیاری كنيد.
اجازه ندهید که این گیاه در آب نشسته و یا مرطوب باقی بماند. این گیاه بهتر است هميشه خشک نگه داشته شود.

🏖این گياه در سايه خوب رشد مي كند.
 اما كمي نور باعث طراوت بيشتري براي آن خواهد شد.
☝️ اما نور دادن بايد منظم باشد.
 در گلخانه هاي حرفه اي براي زاموفيلياها در هفته يكبار مثلا روزهاي يكشنبه به طور مرتب به آن نور ميدهند كه زاموفيليا ها اين نور و انرژي را براي يك هفته در خود ذخيره مي كنند و اين كار باعث قوي شدن گياه در برابر بيماريها میشود.😎
 اين نوع نوردهي به زاموفيليا علاوه بر براق شدن برگها باعث رشد ١/٥ برابري گياه خواهد شد.👍

☝️اما آفتاب ظهر تابستان براي آن بسيار مضر است.

💧سعی کنید با قرار دادن یک تشت پر از آب در کنار گیاه رطوبت آن را تامین کنید البته در روزهای گرم سال هم با غبارپاشی میتونید این نیاز رو برآورده کنید💧

دارای قدرت تسویه کنندگی هوا و از بین برنده سموم محیط😷

این گیاه همیشه سبز و بسیار مقاوم است که از بین بردنش به مراتب سخت تر از نگهداری ان است😮

ارتفاع آن به ۳ متر میرسد🌴😱🌴


#گل #گلهای_آپارتمانی #گیاه #طبیعت


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_07-26-21_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_07-26-21_UTC.jpg
--WebAppBoundary--

###

//Aramesh 3
POST http://localhost:8080/post
Authorization: Bearer VsLLLRC5Fj5CLecQl6Faui1ordB0PIDEpvjZkovL//5NE15gBnOT9EIlcv+QBib3
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

🎁📸

#اصفهان #ایران #ناژوان #طبیعت #عکاسی_طبیعت #حیات_وحش


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_20-47-57_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_20-47-57_UTC.jpg
--WebAppBoundary--

###

//Aramesh 4
POST http://localhost:8080/post
Authorization: Bearer VsLLLRC5Fj5CLecQl6Faui1ordB0PIDEpvjZkovL//5NE15gBnOT9EIlcv+QBib3
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

📸 خاطره ای ثبت شده از تور گیلانگردی
⁦▪️⁩تور اجرا شده هفت چشمه پره سر
⁦🗓️⁩ تاریخ ۹۹/۶/۲۸

#تالش #گردشگری#گردشگر #طبیعت #طبیعتگرد #عکاسی


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-14-13_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-14-13_UTC.jpg
--WebAppBoundary--

###

//Aramesh 5
POST http://localhost:8080/post
Authorization: Bearer VsLLLRC5Fj5CLecQl6Faui1ordB0PIDEpvjZkovL//5NE15gBnOT9EIlcv+QBib3
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

دو نفر هیچوقت همدیگرو

تو یک زمان و یک اندازه

دوست ندارن...

یکیشون وقتی به خودش میاد

که

اون یکی یا حسش وجود نداره

یا

خودش......

#عکس_خاص #طبیعت #آرزو #موزیک #جنگل


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-17-53_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-17-53_UTC.jpg
--WebAppBoundary--

###

//Aramesh 6
POST http://localhost:8080/post
Authorization: Bearer VsLLLRC5Fj5CLecQl6Faui1ordB0PIDEpvjZkovL//5NE15gBnOT9EIlcv+QBib3
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

اکوا ریوم پلی فیش از مرحله ساخت تا راه اندازی، در خدمت شما عزیزان هست.
••••••••••••••••••••••••••••••••••••••••••••••••••••••

۱)ساخت شیشه های ریملس در ابعاد مختلف بدون یک میلخطا

۲)ساخت سامپ و اورفلو و لوله کشی اکواریوم های ابشور ......

۳)راه اندازی اکواریوم های گیاهی از مرحله ساخت تا دکورو... .


‎گل #مدرن #مد #تهران #ایران #دریا# #نور #کادو #طبیعت#


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-23-08_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-23-08_UTC.jpg
--WebAppBoundary--

###

//Aramesh 7
POST http://localhost:8080/post
Authorization: Bearer VsLLLRC5Fj5CLecQl6Faui1ordB0PIDEpvjZkovL//5NE15gBnOT9EIlcv+QBib3
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

میدانی
دلتنگی
عین آتش زیر خاکستر است
گاهی فکر می کنی تمام شده
اما یک دفعه
همه ات را آتش می زند

#آتش #آرامش #طبیعت #دلتنگی


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-24-28_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-24-28_UTC.jpg
--WebAppBoundary--

###

//Aramesh 8
POST http://localhost:8080/post
Authorization: Bearer VsLLLRC5Fj5CLecQl6Faui1ordB0PIDEpvjZkovL//5NE15gBnOT9EIlcv+QBib3
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

عکاسی#پاییز#پاییزی#طبیعت#سرما#مهر#عکس#فصل#🍁🍂


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-27-25_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-27-25_UTC.jpg
--WebAppBoundary--

###

//Aramesh 9
POST http://localhost:8080/post
Authorization: Bearer VsLLLRC5Fj5CLecQl6Faui1ordB0PIDEpvjZkovL//5NE15gBnOT9EIlcv+QBib3
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

:
Listen to the sound of the magical nature and feel the harmony within you.💆‍♀️


گوش کن
صدای زیبا و معجزه بخش طبیعت.
هارمونی را احساس کن.‌
هارمونی که باعث ایجاد آرامش عمیق درونی‌ میشه.

.
#طبیعت #طبیعتگردی #آرامش


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-27-42_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-27-42_UTC.jpg
--WebAppBoundary--

###

//Aramesh 10
POST http://localhost:8080/post
Authorization: Bearer VsLLLRC5Fj5CLecQl6Faui1ordB0PIDEpvjZkovL//5NE15gBnOT9EIlcv+QBib3
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

فردا دیر است ...
امروزت را همین امروز ، زندگی کن !
همین امروز لذتش را ببر ،
و همین امروز برای آرزوهایت تلاش کن ...
حسرت ، یعنی در گذشته جا مانده ای ،
و نگرانی یعنی ، اسیرِ آینده ای شده ای که هنوز نرسیده و اتفاقاتی که هنوز نیفتاده !
آینده ای که شاید نرسد
و اتفاقاتی که شاید نیفتد !
بیخیالِ چیزهایی که نبودنشان کیفیتِ بودنت را کم می کند
آرامش و لبخند را در آغوش بگیر و امروز را همان جوری که دوست داری زندگی کن ...

.
#آرامش #سرسبزی #زیبا #عکاس #پروفایل #طبیعت


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-27-44_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-27-44_UTC.jpg
--WebAppBoundary--

###

//Aramesh 11
POST http://localhost:8080/post
Authorization: Bearer VsLLLRC5Fj5CLecQl6Faui1ordB0PIDEpvjZkovL//5NE15gBnOT9EIlcv+QBib3
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

Delicious autumn! My very soul is wedded to it, and if I were a bird I would fly about the earth seeking the successive autumns.”
– George Eliot .........Photo credit:
#طبیعت #عکاسی


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-29-17_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-29-17_UTC.jpg
--WebAppBoundary--

###

//Aramesh 12
POST http://localhost:8080/post
Authorization: Bearer VsLLLRC5Fj5CLecQl6Faui1ordB0PIDEpvjZkovL//5NE15gBnOT9EIlcv+QBib3
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

.Life is like a mirror; we get the best results when we smile at it." —Unknown

زندگی مانند آینه است . زمانی که به آن می خندیم ، بهترین نتایج را بدست می آوریم.

#کوهنوردی #طبیعت #دنیا #البرز #دماوند


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-29-41_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-29-41_UTC.jpg
--WebAppBoundary--

###

//Aramesh 13
POST http://localhost:8080/post
Authorization: Bearer VsLLLRC5Fj5CLecQl6Faui1ordB0PIDEpvjZkovL//5NE15gBnOT9EIlcv+QBib3
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

طبیعت مظهر قدرت خداوند...
#طبیعت
#ایران


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-30-37_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-30-37_UTC.jpg
--WebAppBoundary--

###

//Aramesh 14
POST http://localhost:8080/post
Authorization: Bearer VsLLLRC5Fj5CLecQl6Faui1ordB0PIDEpvjZkovL//5NE15gBnOT9EIlcv+QBib3
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

نمایی زیبا از لایی شاه رضا از روستای واودین بخش هزارجریب 🤩🌲🏕

#زندگی #تفریح #لذت #طبیعت #طبیعت_زیبا #کوه


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-30-39_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-30-39_UTC.jpg
--WebAppBoundary--

###

//Aramesh 15
POST http://localhost:8080/post
Authorization: Bearer VsLLLRC5Fj5CLecQl6Faui1ordB0PIDEpvjZkovL//5NE15gBnOT9EIlcv+QBib3
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

\#عکس‌ #عکاسی #طبیعت #دشت #ایران #آسمان #کوه

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-31-22_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/nature/2020-09-19_21-31-22_UTC.jpg
--WebAppBoundary--

###