//Phanoos 1
POST http://localhost:8080/post
Authorization: Bearer x/7eW4pWS2NPh0Ka5CF6SMOBpja8bPwBSw7RsbnC9TxvduSwt1MbxQk2pBUwmf4H
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

\#والپیپر

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-07-39_UTC_4.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/wallpaper/2020-09-19_21-07-39_UTC_4.jpg
--WebAppBoundary--
###

//Phanoos 2
POST http://localhost:8080/post
Authorization: Bearer x/7eW4pWS2NPh0Ka5CF6SMOBpja8bPwBSw7RsbnC9TxvduSwt1MbxQk2pBUwmf4H
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

\#والپیپر

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-07-39_UTC_5.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/wallpaper/2020-09-19_21-07-39_UTC_5.jpg
--WebAppBoundary--
###

//Phanoos 3
POST http://localhost:8080/post
Authorization: Bearer x/7eW4pWS2NPh0Ka5CF6SMOBpja8bPwBSw7RsbnC9TxvduSwt1MbxQk2pBUwmf4H
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

\#والپیپر

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-07-39_UTC_7.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/wallpaper/2020-09-19_21-07-39_UTC_7.jpg
--WebAppBoundary--
###

//Phanoos 4
POST http://localhost:8080/post
Authorization: Bearer x/7eW4pWS2NPh0Ka5CF6SMOBpja8bPwBSw7RsbnC9TxvduSwt1MbxQk2pBUwmf4H
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

\#والپیپر

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-07-39_UTC_8.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/wallpaper/2020-09-19_21-07-39_UTC_8.jpg
--WebAppBoundary--
###

//Phanoos 5
POST http://localhost:8080/post
Authorization: Bearer x/7eW4pWS2NPh0Ka5CF6SMOBpja8bPwBSw7RsbnC9TxvduSwt1MbxQk2pBUwmf4H
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

\#والپیپر

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-07-39_UTC_9.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/wallpaper/2020-09-19_21-07-39_UTC_9.jpg
--WebAppBoundary--
###

//Phanoos 6
POST http://localhost:8080/post
Authorization: Bearer x/7eW4pWS2NPh0Ka5CF6SMOBpja8bPwBSw7RsbnC9TxvduSwt1MbxQk2pBUwmf4H
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

کیا از این دسته پورفایلا میخواستن 😍😍
 Who wanted these profiles?
#والپیپر

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-41-03_UTC_2.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/wallpaper/2020-09-19_21-41-03_UTC_2.jpg
--WebAppBoundary--
###

//Phanoos 7
POST http://localhost:8080/post
Authorization: Bearer x/7eW4pWS2NPh0Ka5CF6SMOBpja8bPwBSw7RsbnC9TxvduSwt1MbxQk2pBUwmf4H
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

\#والپیپر

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-41-03_UTC_5.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/wallpaper/2020-09-19_21-41-03_UTC_5.jpg
--WebAppBoundary--
###