//Max_Pic 1
POST http://localhost:8080/post
Authorization: Bearer FaZI3j20Hf9JoFxzcN98COZsvEBVeW9TAjI64MtF2OfbY1tF0Qrf8wuMAO9timNo
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

🍃
#عکاسی#منظره

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-21-10_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/view/2020-09-19_19-21-10_UTC.jpg
--WebAppBoundary--
###

//Max_Pic 2
POST http://localhost:8080/post
Authorization: Bearer FaZI3j20Hf9JoFxzcN98COZsvEBVeW9TAjI64MtF2OfbY1tF0Qrf8wuMAO9timNo
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

.
#منظره #طبیعت #دریا

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-25-26_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/view/2020-09-19_19-25-26_UTC.jpg
--WebAppBoundary--
###

//Max_Pic 3
POST http://localhost:8080/post
Authorization: Bearer FaZI3j20Hf9JoFxzcN98COZsvEBVeW9TAjI64MtF2OfbY1tF0Qrf8wuMAO9timNo
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

Photo by:zeynab rafati
#منظره

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-30-01_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/view/2020-09-19_19-30-01_UTC.jpg
--WebAppBoundary--
###

//Max_Pic 4
POST http://localhost:8080/post
Authorization: Bearer FaZI3j20Hf9JoFxzcN98COZsvEBVeW9TAjI64MtF2OfbY1tF0Qrf8wuMAO9timNo
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

📌 جزیره هرمز - هرمزگان - ایران
📌 Hormuz Island, Hormozgan, Iran
.
.
#طبیعت #ایران


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-34-49_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/view/2020-09-19_19-34-49_UTC.jpg
--WebAppBoundary--
###

//Max_Pic 5
POST http://localhost:8080/post
Authorization: Bearer FaZI3j20Hf9JoFxzcN98COZsvEBVeW9TAjI64MtF2OfbY1tF0Qrf8wuMAO9timNo
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

نقاشی رنگ روغن از طبیعت 🎨🎨🎨🎨🌻🌻🌻
#منظره

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-38-38_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/view/2020-09-19_19-38-38_UTC.jpg
--WebAppBoundary--
###

//Max_Pic 6
POST http://localhost:8080/post
Authorization: Bearer FaZI3j20Hf9JoFxzcN98COZsvEBVeW9TAjI64MtF2OfbY1tF0Qrf8wuMAO9timNo
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

🌹🌷🌹
🔹 كد : شماره 11c
🔸 نام اثر : دهکده سرچشمه
🔹 تراکم بافت : ۵۰ رج
🔸 جنس چله : ابریشم
🔹 جنس قاب : PVC
#گل #منظره

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-38-39_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/view/2020-09-19_19-38-39_UTC.jpg
--WebAppBoundary--
###

//Max_Pic 7
POST http://localhost:8080/post
Authorization: Bearer FaZI3j20Hf9JoFxzcN98COZsvEBVeW9TAjI64MtF2OfbY1tF0Qrf8wuMAO9timNo
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

🌹🌷🌹
🔹 كد : شماره 11c
🔸 نام اثر : گل طولی ترمه طرح لاله و بابونه
🔹 تراکم بافت : ۵۰ رج
🔸 جنس چله : ابریشم
🔹 جنس قاب : PVC
🔸 ابعاد تابلو با قاب سایز: ١٠٧*۶۴
#گل #منظره

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-43-54_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/view/2020-09-19_19-43-54_UTC.jpg
--WebAppBoundary--
###

//Max_Pic 8
POST http://localhost:8080/post
Authorization: Bearer FaZI3j20Hf9JoFxzcN98COZsvEBVeW9TAjI64MtF2OfbY1tF0Qrf8wuMAO9timNo
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

\#طبیعت #تابستان #خورشید #شب #درخت #زیبا #آبی
#طبیعتگرد #منظره

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-46-11_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/view/2020-09-19_19-46-11_UTC.jpg
--WebAppBoundary--
###

//Max_Pic 9
POST http://localhost:8080/post
Authorization: Bearer FaZI3j20Hf9JoFxzcN98COZsvEBVeW9TAjI64MtF2OfbY1tF0Qrf8wuMAO9timNo
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

\#طبیعت #تابستان #خورشید #شب #درخت #زیبا #آبی
#طبیعتگرد #منظره

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-48-03_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/view/2020-09-19_19-48-03_UTC.jpg
--WebAppBoundary--
###
