//CityAway 1
POST http://localhost:8080/post
Authorization: Bearer uE6spJK1+X9QWqTEgtABq9z4aaBmwRfonHj2/pzWv7zlJ5T8Q9YqjAcBWBBz5AgK
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

.
توکایی در قفس
نیما یوشیج
نقاشی از بهمن دادخواه
ناشر؛ کانون پرورش فکری کودکان و نوجوان
تاریخ چاپ؛ ۱۳۵۲
چاپ اول

#شاهنامه #فردوسی

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_18-09-33_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sea/2020-09-19_18-09-33_UTC.jpg
--WebAppBoundary--

###

//CityAway 2
POST http://localhost:8080/post
Authorization: Bearer uE6spJK1+X9QWqTEgtABq9z4aaBmwRfonHj2/pzWv7zlJ5T8Q9YqjAcBWBBz5AgK
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

.
روبن هود
نویسنده؛ چارلز ویویان
مترجم؛ محسن فارسی
ناشر؛ انتشارات گوتنبرگ
تاریخ چاپ؛ ۱۳۳۹
چاپ اول
#شاهنامه #فردوسی


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_18-10-28_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sea/2020-09-19_18-10-28_UTC.jpg
--WebAppBoundary--

###
//CityAway 3
POST http://localhost:8080/post
Authorization: Bearer uE6spJK1+X9QWqTEgtABq9z4aaBmwRfonHj2/pzWv7zlJ5T8Q9YqjAcBWBBz5AgK
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

Gullivers travels
سفرهای گالیور
نویسنده؛
Jonathan Swift
#شاهنامه #فردوسی

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_18-11-16_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sea/2020-09-19_18-11-16_UTC.jpg
--WebAppBoundary--

###

//CityAway 4
POST http://localhost:8080/post
Authorization: Bearer uE6spJK1+X9QWqTEgtABq9z4aaBmwRfonHj2/pzWv7zlJ5T8Q9YqjAcBWBBz5AgK
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

.
بابا گوریو
نویسنده؛ بالزاک
مترجم؛ م.ا. به آذین
ناشر؛ سازمان کتابهای جیبی
تاریخ چاپ؛ ۱۳۴۱

#شاهنامه #فردوسی


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_18-11-43_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sea/2020-09-19_18-11-43_UTC.jpg
--WebAppBoundary--

###

//CityAway 5
POST http://localhost:8080/post
Authorization: Bearer uE6spJK1+X9QWqTEgtABq9z4aaBmwRfonHj2/pzWv7zlJ5T8Q9YqjAcBWBBz5AgK
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

.
#ایران #فارسی #شاهنامه #فردوسی
#زیبا #ادبیات

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_18-13-34_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sea/2020-09-19_18-13-34_UTC.jpg
--WebAppBoundary--

###

//CityAway 6
POST http://localhost:8080/post
Authorization: Bearer uE6spJK1+X9QWqTEgtABq9z4aaBmwRfonHj2/pzWv7zlJ5T8Q9YqjAcBWBBz5AgK
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

.📚#ketab_kamyabb
📖 اسم کتاب : آئینه
✏نویسنده : محمد حجازی
📠انتشارات : بهزاد
⌚تاریخ چاپ : 1386
چاپ اول

این مجموعه حاوی مقالاتی است ادبی از مرحوم "محمد حجازی" نویسنده‌ی معاصر که در قالب خاطره و داستان به نگارش درآمده و عناوین برخی از آن‌ها عبارت است از: "شیرین کلا"، "یک فیلسوف بزرگ"، "معالجه‌ی امراض روحی"، "مجلس عیادت"، "آسایش زندگی"، "کشف ادبی"، "تفرج نوروز"، "کتاب لغت"، "مجمع زندانیان"، "سعدی و حافظ" و "مارگیر". برای نمونه، "مارگیر"، روایت زنی است که در حومه‌ی شهر ساکن است. او روزی متوجه صدایی می‌شود که از صندوق‌خانه به گوش می‌رسد. در این حال به طرف صندوق‌خانه حرکت کرده و متوجه می‌شود که دزدی مشغول جمع کردن وسایل داخل صندوق‌خانه است. وی برای فرار از دزد، به ایوان رفته، اما در ایوان به ماری برمی‌خورد. زن با دیدن مار از هوش رفته و زمانی که به هوش می‌آید، متوجه می‌شود که دزد، مار را کشته و هیچ‌یک از وسایل خانه را به سرقت نبرده است. زن با فهمیدن این موضوع، مبلغی پول به دزد داده و می‌گوید که هر وقت نیاز مالی پیدا کردی به منزل من بیا. از آن به بعد مارگیر، ماهی یک‌بار به منزل زن آمده و مبلغی پول از او می‌گرفت.

#شاهنامه #کتابفروشی


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_18-59-23_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sea/2020-09-19_18-59-23_UTC.jpg
--WebAppBoundary--

###

//CityAway 7
POST http://localhost:8080/post
Authorization: Bearer uE6spJK1+X9QWqTEgtABq9z4aaBmwRfonHj2/pzWv7zlJ5T8Q9YqjAcBWBBz5AgK
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

\#هر_ایرانی_یک_نام_آریایی
‌نام هایی که با «آ،ا» آغاز میشوند:
‌
آبان دخت : دخترآبان ‌
‌
آبتين : نام پدر فريدون پادشاه پيشدادي
‌
آتوسا : قدرت و توانمندي - دختر کوروش
‌
آفره دخت : دختر آتش - دختري که در ماه آذر به دنيا آمده است .
‌
آذرنوش‌: شيرين و دل انگيز
‌
آذين : زيور
‌
آرش: درخشان ، آفتاب ‌
‌
آرتین: عاقل و زیرک
‌
آرشام : بسيار قوي
‌
آرمان : آرزو - خواهش - اميد
‌
آرمين : آرام گرفتن
‌ ‌
آرميتا: آرامش يافته ، کلمه اي زردشتي است
‌
آريا فر: دارنده شکوه آريائي
‌
آريا : آزاده نجيب - يکي از پادشاهان ماد
‌
آريا مهر : دارنده مهر ايران
‌
آرين : سفيد پوست آريائي
‌
آزاده : دلير و بي باک ، رها
‌
آزرم : شرم ، مهر ، محبت ، عشق
‌
آزرمدخت : يکي از ملکه هاي ساساني
‌
آزيتا : آزاده
‌
آناهيتا : الهه آب
‌
آيدا : شاد
‌
اختر : ستاره
‌
ارد شير : شير زيبا
‌ ‌
اردوان : نام پادشاهان معروف اشکاني
‌
ارنواز: نوازش شده اهورا - دختر جمشيد شاه پيشدادي
‌
اسفنديار : پاک آفريده شده ‌
‌
اشکان : منسوب به اشک - بنيانگذار سلطنت پارتها
‌‌
افشين : با همت ‌
‌
انوش (‌ آنوشا ) : استوار و جاويد
‌
انوشروان : دارنده لوح جاويدان - لفب خسرو اول پادشاه ساساني
‌
اوستا : نام کتاب آسماني زردشت
‌
اهورا : صاحب ، فرمانرواي دانا
‌
ايراندخت : دختر ايران
‌
ايرج : ياري دهنده آريائيها - پسرفريدون ، پادشاه و پهلوان ايراني
‌
ايزديار : کشي که خداوند يار اوست
#ایران


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-19-56_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sea/2020-09-19_19-19-56_UTC.jpg
--WebAppBoundary--

###

//CityAway 8
POST http://localhost:8080/post
Authorization: Bearer uE6spJK1+X9QWqTEgtABq9z4aaBmwRfonHj2/pzWv7zlJ5T8Q9YqjAcBWBBz5AgK
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

ا

ترکیب دلال و خیار  تو ماست😋😋

دلال به دلیل طبع گرمی که داره مصلح غذاهای سرده و علاوه بر طعم خیلی خوبی که به ماست میده بسیار مفید و پر خاصیته چون  ترکیبی از سبزی های تازه و متنوعه😊😊😊

و متناسب با خواسته و ذائقه ی شما سیر و نمکش تنظیم میشه😊😊
#زیبا

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-24-33_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sea/2020-09-19_21-24-33_UTC.jpg
--WebAppBoundary--

###

//CityAway 9
POST http://localhost:8080/post
Authorization: Bearer uE6spJK1+X9QWqTEgtABq9z4aaBmwRfonHj2/pzWv7zlJ5T8Q9YqjAcBWBBz5AgK
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

دشت آفتاب گردان کالپوش-شاهرود
جاهای دیدنی و بکر ایران و جهان

#طبیعت
#آبشار
#گل
#دریا
#کوه
#جنگل


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-47-04_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sea/2020-09-19_21-47-04_UTC.jpg
--WebAppBoundary--

###

//CityAway 10
POST http://localhost:8080/post
Authorization: Bearer uE6spJK1+X9QWqTEgtABq9z4aaBmwRfonHj2/pzWv7zlJ5T8Q9YqjAcBWBBz5AgK
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

تفاوت و حال میکنین 😎😎
#دریا

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-51-32_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sea/2020-09-19_21-51-32_UTC.jpg
--WebAppBoundary--

###

//CityAway 11
POST http://localhost:8080/post
Authorization: Bearer uE6spJK1+X9QWqTEgtABq9z4aaBmwRfonHj2/pzWv7zlJ5T8Q9YqjAcBWBBz5AgK
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

\#طلوع #دریا

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-54-52_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sea/2020-09-19_21-54-52_UTC.jpg
--WebAppBoundary--

###

//CityAway 12
POST http://localhost:8080/post
Authorization: Bearer uE6spJK1+X9QWqTEgtABq9z4aaBmwRfonHj2/pzWv7zlJ5T8Q9YqjAcBWBBz5AgK
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

میخواهم ملوان کشتی دریاهای نامعلوم شوم، تا همراه امواج دریا به سرزمین دیگر یا حتی جهان دیگری بروم ...
🚢🌊
.
.

#عکس #عکاسی #دریا #طبیعت #تهران #پروفایل


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-58-10_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sea/2020-09-19_21-58-10_UTC.jpg
--WebAppBoundary--

###
