s//Famile_Door 1
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

.
#کوه #دریا #آسمان

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-39-13_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_19-39-13_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 2
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

.
#کوه #دریا #آسمان

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-39-58_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_19-39-58_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 3
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

درخت سیبی که روایت شده اسحاق نیوتن در زیر آن درخت نشسته بود و سیبی روی سرش افتاد و جاذبه را کشف کرد.
.
.
‌
‌.
‌
.
پیج ما رو فالوو کنید👇👇
.
#زمین #خورشید
#آسمان  #ایران


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-42-35_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_19-42-35_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 4
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

.
#کوه #دریا #آسمان

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-42-44_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_19-42-44_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 5
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

\#طبیعت #تابستان #شب #درخت #زیبا #آبی

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-46-11_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_19-46-11_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 6
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

\#طبیعت #تابستان #خورشید #غروب#شب #درخت #هوا #زیبا #آبی


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-48-03_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_19-48-03_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 7
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

\#طبیعت #تابستان #خورشید #غروب #شب #درخت #هوا #زیبا #آبی

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-48-43_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_19-48-43_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 8
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

☾




▪️حتی زمینم بدون ماهش تنهاست ،
▪️من هم  بدون تو تنهام....



	[00:20]



_________________________________
#آسمان #مهتابی
#ماه #غروب #جدایی #تیره

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-50-28_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_19-50-28_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 9
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

\#طبیعت #تابستان #خورشید #غروب #شب #درخت #زیبا #آبی


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-52-59_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_19-52-59_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 10
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

❅✿🍃🦋🍃✿❅
دلم یک دوست می‌خواهد
که اوقاتی که دلتنگم
بگوید: خانه را ول کن
بگو من کی، کجا باشم؟

❅✿🍃🦋🍃✿❅
.
.
.
‌.
.
#پروفایل #آسمان#آرامش

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_19-57-41_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_19-57-41_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 11
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

\#سرد_ترین مکان کشف شده در #سحابی زیبای بومرنگ ۲۷۲- درجه زیر صفر 😶
‌
 #سحابی سر اسب در #صورت_فلکی شکارچی واقع شده است
‌
از کدوم #سحابی خوشتون اومده ؟؟😍
‌
بازم پست از #سحابی ها بزارم ؟؟
‌
‌
#زمین #آسمان #شب #نجوم
‌



--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_20-03-36_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_20-03-36_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 12
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

باسلام
یکی از نکات قابل توجه و جذاب در سفرهای کویری و اقامت در بوم گردی های سراسر کشور عزیزمان ایران،دورهمی های دوستانه و تبادل نظر و تجربه درباره مسائل گوناگون است. اقامتگاه بوم گردی برج ستاره کویر دارای فضا های متنوع و جذابی میباشد که این امکان را در اختیار گردشگران قرار میدهد تا به دور از هیاهو و به صورت اختصاصی از فضای موجود بهره برده و لحظات خوشی را در کنار هم رقم بزنند...
فضایی سنتی که برای برخی یاد آور خاطراتی قدیمی و برای برخی تجربه ای نو و بی بدیل است...
...کویر را باید دید...

#ستاره #عکاسی #آسمان #طبیعتگردی

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_20-17-54_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_20-17-54_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 13
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

مجنون نگه دار مرا..⁦❤️⁩
.
.
.
👈 پست ها و پیج مارو لایک و فالو کنید.
.
#آرامش

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_20-19-25_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_20-19-25_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 14
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

بنظر من سقف ها خیلی مهمن🌙🍃
__________________

مهم تر از زمینی که روش راه میریم...تاحالا فکر کردین بهش؟
وارد یه جایی میشیم اصلا به سقف حتی یه نگاهم نمیندازیمو اصلا به چشم نمیاد...ولی همه دنبال همین سقفیم وقتی که بارون شدید میباره...
فک میکنم بعضی آدم ها تو زندگیمون شبیه همین سقفان...کم میبینیمشون...کم توجهی میکنیم...حواسمون نیست که هستن ...ولی وقتی بارون مشکلا شدید میشه پناه میبریم بهشون...
شما شاید دقت نکرده باشین ولی سقفا خیلی قشنگن ...اکثرا مستطیلن...یا مثل سقفای چند ضلعیه و بی قید و شرط ...یه دونه سقفم که بالای سر هممون هست...همین آسمون آبی که واسه هممون عادی شده ...
بیشتر به سقفا توجه کنید...بعضی وقتا یچیزایی اونجا هست که رو زمین پیدا نمیشه ....یه سقف آبی روشن با چنتا تیکه پنبه سفیدو چنتا هفتو هشته تیره اون دور، یه قرص نقره ای وچنتا دونه پرنده معلق...

_________________
#آسمان


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_20-32-41_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_20-32-41_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 15
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

❅✿🍃🦋🍃✿❅

.
چه نیازیست به این زلزله ها، یک عمریست
دل تنگ من از این فاصلـــه ها می لرزد...!
.
#پروفایل #آسمان #جاده


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_20-34-48_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_20-34-48_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 16
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

آسمون امروز از بس که تیکه تیکه بود میشد صداش زد جگر زلیخا
عین یه تابلوی نقاشی که هیچوقت نمیشه ازش سیر شد جلو چشمام دلبری میکرد
انگار می دونست چشم و دلم سیر نمیشه از تماشاش، هر چی به غروب نزدیکتر می شد جذابتر میشد با اون رنگ ارغوانی بی نظیرش
خدا  ماهرانه روش قلم میزد و من براش میخواندم
(گفته بودی که چرا محو تماشای منی
آنچنان محو که یک دم مژه بر هم نزنی
مژه برهم نزنم تا که ز دستم نرود
ناز چشم تو به قدر مژه برهم زدنی)
این بود وصف زیبایی آسمون
و یه پسر طناب بدست صدام می زد که بیا دنبالم بریم مرغابی ها رو تماشاکنیم و من ناگزیر دل کندم از این زیبای دوست داشتنی و محو تماشای مرغابی هایی شدم که آخرین آب تنی رو میکردن قبل غروب تو دل آبیه استخر
#آسمان

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_20-34-55_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_20-34-55_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 17
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

مروری بر دیدنیهای زیبای ییلاقات استان گیلان

#آسمان
#ایرانگردی
#ایران


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_20-39-10_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_20-39-10_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 18
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain



--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_20-40-32_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_20-40-32_UTC.jpg
--WebAppBoundary--

###

//Famile_Door 19
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

یا الهی پناهم بده🙏

#آسمان


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_20-42-53_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_20-42-53_UTC.jpg
--WebAppBoundary--
###

//Famile_Door 20
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

گفتم شاید براتون جالب باشه و اینو یه جا ندیده بودین تابحال...😊
اینم بگم قله ارفع کوه از دوقله دیگه مرتفع تره...❤️

عکسای خوبتون رو برامون بفرستین🙏🏻
و مارو به دوستانتون معرفی کنین.
#طبیعت #آسمان #گل #درخت


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_20-49-05_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_20-49-05_UTC.jpg
--WebAppBoundary--
###

//Famile_Door 21
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

...
به یاد داشته باش
اگرتوبه کسی
خوبی کردی؛
مواظب باش یادآوری نکنی.....
واگر شخصی به
تو نیکی کرد؛
مواظب باش فراموش نکنی
#آسمان #عکاسی


--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-04-47_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_21-04-47_UTC.jpg
--WebAppBoundary--
###

//Famile_Door 22
POST http://localhost:8080/post
Authorization: Bearer 4WfSwStKHAoPjFF/MgjQDKbiwMgPof0EDgNJBhzoYrhpryDHGxM4qYIzsy7vo+Rk
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="content";
Content-Type: text/plain

.
‌#عکاسی #طبیعت #ایران #آسمان #کوه

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2020-09-19_21-31-22_UTC.jpg"
Content-Type: image/jpeg

< C:/Users/[UserName]/Documents/DATA/sky/2020-09-19_21-31-22_UTC.jpg
--WebAppBoundary--
